INSERT INTO sector (`name`) VALUES ('Landbouw, jacht en visserij');
INSERT INTO sector (`name`) VALUES ('Winning van delfstoffen');
INSERT INTO sector (`name`) VALUES ('Productie en distributie van en handel in elektriciteit, aardgas, stoom en gekoelde lucht');
INSERT INTO sector (`name`) VALUES ('Industrie');
INSERT INTO sector (`name`) VALUES ('Winning en distributie van water; afval- en afvalwaterbeheer en sanering');
INSERT INTO sector (`name`) VALUES ('Bouwnijverheid');
INSERT INTO sector (`name`) VALUES ('Groot- en detailhandel, reparatie van auto’s');
INSERT INTO sector (`name`) VALUES ('Vervoer en opslag');
INSERT INTO sector (`name`) VALUES ('Logies-, maaltijd- en drankverstrekking');
INSERT INTO sector (`name`) VALUES ('Informatie en communicatie');
INSERT INTO sector (`name`) VALUES ('Financiële instellingen');
INSERT INTO sector (`name`) VALUES ('Verhuur van en handel in onroerend goed');
INSERT INTO sector (`name`) VALUES ('Advisering, onderzoek en overige specialistische zakelijke dienstverlening');
INSERT INTO sector (`name`) VALUES ('Verhuur van roerende goederen en overige zakelijke dienstverlening');
INSERT INTO sector (`name`) VALUES ('Openbaar bestuur, overheidsdiensten en verplichte sociale verzekeringen');
INSERT INTO sector (`name`) VALUES ('Onderwijs');
INSERT INTO sector (`name`) VALUES ('Gezondheids- en welzijnszorg');
INSERT INTO sector (`name`) VALUES ('Cultuur, sport en recreatie');
INSERT INTO sector (`name`) VALUES ('Overige dienstverlening');
